### ISSUE TITLE
Allow option to redirect all requests to a s3 website bucket

### ISSUE THREAD

**Issue by sarkis** [cloudposse/terraform-aws-s3-website#23]
Currently, the `redirect_all_requests_to` parameter for the `aws_s3_bucket` resource cannot be set. I propose we add this parameter, thereby enabling this module to be used in creating s3 website buckets with the sole purpose of redirecting requests. 

https://www.terraform.io/docs/providers/aws/r/s3_bucket.html#redirect_all_requests_to

**Comment by sarkis** [comment]
@osterman I can PR this up - let me know if you think this was left out by design (and don't want this in..)

**Comment by osterman** [comment]
Sounds good to me!
