### ISSUE TITLE
Changes to default S3 settings cause module to fail

### ISSUE THREAD

**Issue by ihemingway** [cloudposse/terraform-aws-s3-website#84]
Pardon my improper form, but changes to the default settings for S3 buckets are causing this module to fail:

https://github.com/cloudposse/terraform-aws-s3-website/blob/master/main.tf#L47

https://docs.aws.amazon.com/AmazonS3/latest/userguide/create-bucket-faq.html

'Starting in April 2023, Amazon S3 will change the default settings for S3 Block Public Access and S3 Object Ownership (ACLs disabled) for all new S3 buckets.'

It results in this error:

Error: Error creating S3 bucket: InvalidBucketAclWithObjectOwnership: Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting

**Comment by jl-cayuse** [comment]
I wanted to bump this issue. It's causing significant issues getting infrastructure released on my side.
